/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei/core/useGLTF'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('Miami_Street_web.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0.49, 1.7, -5.46]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={0.5} decay={2} color="#59ff5b" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.49, 1.7, -2.55]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={1} decay={2} color="#4cff5a" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.44, 1.66, -0.28]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={0.5} decay={2} color="#4cff54" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[0.39, 1.69, 2.58]} rotation={[1.89, 0.88, -2.05]}>
        <pointLight intensity={0.5} decay={2} color="#60ff67" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.36, 0.6, -2.57]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.19, 0.49, -1.14]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.25, 0.35, 0.22]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.26, 0.48, 1.28]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.16, 0.42, 2.36]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.18, 0.4, 3.95]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.18, 0.4, 4.95]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[3.18, 0.44, 6.04]} rotation={[0, 0, 0.22]}>
        <spotLight intensity={1} angle={0.7} penumbra={0.15} decay={2} rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-5.69, 2.64, -8.72]}>
        <pointLight intensity={0.5} decay={2} color="#37ff2e" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <group position={[-6.07, 2.15, -8.34]}>
        <pointLight intensity={0.5} decay={2} color="#ff0a0b" rotation={[-Math.PI / 2, 0, 0]} />
      </group>
      <mesh geometry={nodes.textured.geometry} material={nodes.textured.material} rotation={[Math.PI / 2, 0, 0]} />
      <group position={[0.45, 1.2, -3.95]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.47]}>
        <mesh geometry={nodes.StreetDetails_08004_1.geometry} material={nodes.StreetDetails_08004_1.material} />
        <mesh geometry={nodes.StreetDetails_08004_2.geometry} material={nodes.StreetDetails_08004_2.material} />
        <mesh geometry={nodes.StreetDetails_08004_3.geometry} material={nodes.StreetDetails_08004_3.material} />
        <mesh geometry={nodes.StreetDetails_08004_4.geometry} material={nodes.StreetDetails_08004_4.material} />
      </group>
      <group position={[0.4, 1.21, 1.13]} rotation={[Math.PI / 2, 0, 0]} scale={[1, 1, 0.47]}>
        <mesh geometry={nodes.StreetDetails_08005.geometry} material={nodes.StreetDetails_08005.material} />
        <mesh geometry={nodes.StreetDetails_08005_1.geometry} material={materials['Sign_emergency.001']} />
        <mesh geometry={nodes.StreetDetails_08005_2.geometry} material={nodes.StreetDetails_08005_2.material} />
        <mesh geometry={nodes.StreetDetails_08005_3.geometry} material={nodes.StreetDetails_08005_3.material} />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.003']}
        position={[2.95, 1.14, 1.18]}
        rotation={[0, -0.02, 1.57]}
        scale={[0.45, 1, 5.58]}
      />
      <mesh
        geometry={nodes.Text.geometry}
        material={materials['Material.005']}
        position={[2.91, 0.75, -3.11]}
        rotation={[1.57, 0, 1.58]}
        scale={[0.76, 1, 0.7]}
      />
      <group position={[-0.11, -2.71, -5.42]} rotation={[Math.PI / 2, 0, 3.14]} scale={[0.84, 0.85, 0.65]}>
        <mesh geometry={nodes.StreetDetails_08006_1.geometry} material={materials['StreetLight_Metal.002']} />
        <mesh geometry={nodes.StreetDetails_08006_2.geometry} material={materials['Sign_DontWalk.002']} />
        <mesh geometry={nodes.StreetDetails_08006_3.geometry} material={materials['Sign_GrandSt.002']} />
        <mesh geometry={nodes.StreetDetails_08006_4.geometry} material={materials['Sign_WBroadway.002']} />
        <mesh geometry={nodes.StreetDetails_08006_5.geometry} material={materials['Sign_Walk.002']} />
        <mesh geometry={nodes.StreetDetails_08006_6.geometry} material={materials['StreetLight_Red.002']} />
        <mesh geometry={nodes.StreetDetails_08006_7.geometry} material={materials['StreetLight_Green.002']} />
        <mesh geometry={nodes.StreetDetails_08006_8.geometry} material={materials['Metal_GreenB.002']} />
        <mesh geometry={nodes.StreetDetails_08006_9.geometry} material={materials['StreetLight_GreenOff.002']} />
        <mesh geometry={nodes.StreetDetails_08006_10.geometry} material={materials['StreetLight_YellowOff.002']} />
        <mesh geometry={nodes.StreetDetails_08006_11.geometry} material={materials['StreetLight_RedOff.002']} />
      </group>
      <mesh
        geometry={nodes.Text001.geometry}
        material={nodes.Text001.material}
        position={[0, -0.17, -4.89]}
        rotation={[Math.PI / 2, 0, 1.56]}
        scale={[0.13, 0.14, 0.13]}
      />
      <mesh
        geometry={nodes.Text002.geometry}
        material={nodes.Text002.material}
        position={[0.82, -0.18, -5.35]}
        rotation={[Math.PI / 2, 0, -3.14]}
        scale={[0.13, 0.14, 0.13]}
      />
      <mesh
        geometry={nodes.textured001.geometry}
        material={nodes.textured001.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.textured002.geometry}
        material={nodes.textured002.material}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/Miami_Street_web.glb')
